### ISSUE TITLE
Compile and update member list

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/discord-bot#31]
generate a list of members, sorted by their hardware role (PS4/XBOX/PC) to allow cross referencing with Guilded

**Comment by MarcTowler** [comment]
Add a !divisionlist command for Pegasus, Cyngus etc

**Comment by Redous-UK** [comment]
member list export to CSV 

[csv.zip](https://github.com/MarcTowler/discord-bot/files/2834556/csv.zip)

**Comment by MarcTowler** [comment]
Tested the zip and it works, need to now pull in guilded, find the matches and then output to csv just the users that do not match

**Comment by MarcTowler** [comment]
Any update please @Redous-UK

**Comment by MarcTowler** [comment]
ill check the PR this week, @Kayowin you fine with a discord CSV, a Guilded CSV to compare?

**Comment by MarcTowler** [comment]
No longer needed since split from Guilded
