### ISSUE TITLE
Emoji's break archive

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/discord-bot#36]
![image](https://user-images.githubusercontent.com/1121980/52377935-3110fc80-2a5e-11e9-8529-44eb1ed1cd1a.png)

says it all

**Comment by MarcTowler** [comment]
@Redous-UK do you think you could handle this one, I know it is ear marked for the re-write but could be good to get a fix in place now

**Comment by Redous-UK** [comment]
Replace the below in the else statement should work.  This might prevent Sig or anyone with non alphabetical lets in there name. should really use message.author.id but until this can be changed on the API end points the below should work
`            let shifted = args.slice(3).join(" ");
			let dirtyString = `${message.author.username}`
			let cleanuser = dirtyString.replace(/[^a-zA-Z0-9]/g, "");
			
            https.get(`https://api.itslit.uk/G4G/archive/${args[0]}/${args[1]}/${args[2]}/${cleanuser}/true/${shifted}`, (resp) => {
                let data = '';`

**Comment by MarcTowler** [comment]
this helped a bit!
