### ISSUE TITLE
Points Integration into Azure

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/discord-bot#40]
Currently Point based commands are called onto the [ItsLit API](https://github.com/Design-Develop-Realize/api) which has them stored in a database. Need to look at moving this over to the azure site and removing the dependency on ItsLit API

**Comment by MarcTowler** [comment]
Commands currently handled by API and needs moving to Azure:

1. Points Add
2. Points Remove
3. Prestige
4. Retrieve single user points (can be own or someone else)
5. Retrieve Top 10 points (if user is outside of top10, show the 10 and then show the user, their position and points)

This is across all 3 tables, name, rank, points, prestige count are pieces of info needed

**Comment by kolkonos** [comment]
API on azure for points has been completed and deployed.

**Comment by MarcTowler** [comment]
Will be live in the bot before end of Feb

**Comment by MarcTowler** [comment]
This is now deployed, top10 still to be implements but it is rarely ever used
