### ISSUE TITLE
Endpoint Access for Azure

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/discord-bot#41]
Currently awaiting details for access to Azure via a couple of endpoints... 

1) Points endpoint for #40 
2) Archive endpoint for event archiving.

Awaiting information from Kolk

**Comment by kolkonos** [comment]
Currently working on the revamp of point system to add clan specific Eligible events for event creation template. 
Once that is complete I can work on the api end point to access the CreateEvent end point. 
We need a list of steps for the bot. I’m thinking the bot pulls the list of eligible events as json and then works internally to build out the body of the event request.

**Comment by kolkonos** [comment]
Points end point complete.
