### ISSUE TITLE
Live Stream Announcement

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/discord-bot#42]
Add ability to have going live messages added to #member_streams channel.

Feature would need the following:

- Ability to add live streams
- Ability to Remove Live Streams
- Listening for streams to go live
- Multi-platform (Twitch, Mixer, DLive, Youtube)

**Comment by MarcTowler** [comment]
```JavaScript
client.on('presenceUpdate', (oldMember, newMember) => {
  // check newMember.presence.game.streaming
  // compare with oldMember.presence.game.streaming to see if they just started streaming
  // then check to see if they are on our shoutout list, if so post to #474495887259729920
});
```

**Comment by MarcTowler** [comment]
Any update on this one @Redous-UK ?

**Comment by Redous-UK** [comment]
I have some code but need to test it before doing a PR as per instructions.

**Comment by Redous-UK** [comment]
Tested, confirmed working code sent to Killer for upload.

**Comment by MarcTowler** [comment]
re-opening as it was just spamming

**Comment by MarcTowler** [comment]
Fixed in a simple manner... Just need to teach council how to add streamers
