### ISSUE TITLE
Azure integration - actions list

### ISSUE THREAD

**Issue by kolkonos** [MarcTowler/discord-bot#45]
For editing an officer event:
Once it’s on azure, the bot will have a command that returns the user’s events on azure, as a numbered list. The officer picks a number and the bot asks “what would you like to change.” Officer might type “cancel event” and the bot updates azure

**Comment by VictorNguyen00** [comment]
Can we do number/title?

**Comment by VictorNguyen00** [comment]
Other commands or updates that can be entered?
Canceled
Event Change (i.e. Raid to IB for example)
Delete

**Comment by Redous-UK** [comment]
More information required not sure when this was discussed.

**Comment by MarcTowler** [comment]
@kolkonos does this still need to be open? Never worked out if we wanted to go ahead with this

**Comment by kolkonos** [comment]
@MarcTowler Nah.... we have pretty much migrated all of those things to azure

**Comment by MarcTowler** [comment]
ok closed
