### ISSUE TITLE
Suggestion: Audit Logs

### ISSUE THREAD

**Issue by Redous-UK** [MarcTowler/discord-bot#47]
As discord fails to log certain events (I.E user leaves, error responses, commands parsed) potentially have an audit log channel accessible by Web Team and Clan Council logging all events.

Some functionality we have DM's Marc the error response <----- all this information in the channel etc etc

**Comment by MarcTowler** [comment]
Need a moderation channel for the logging provided by @P-Rigz and we can go ahead with this

**Comment by Redous-UK** [comment]
Channel ID: 544812700459335680  - #bot_logs
