### ISSUE TITLE
Maintenance / Online message

### ISSUE THREAD

**Issue by Redous-UK** [MarcTowler/discord-bot#49]
when servicing bot makes an announcement in web-team channel.
```My Master has finished updating my internal core, I am now available ```
```My Master has retired my services to update my internal core, please be patient```

**Comment by MarcTowler** [comment]
Passing this one over to you @Redous-UK

**Comment by Redous-UK** [comment]
Why me lol, It was my idea :D okay nvm I will see what i can do.

**Comment by MarcTowler** [comment]
haha makes it even more worth passing to you

**Comment by Redous-UK** [comment]
okay looking into this it is possible when doing so via command line only as the .on('disconnect' blah blah code will constantly report these messages due to how discord is designed. Discord refer gateway packets as heartbeats which are sent to keep the connection open. Each heartbeat will typically disconnect and reconnect throwing our comments even though the bot does not go offline or online each time commands are held up in a queue which is inevitably parsed when the heartbeat is reconnected. So we can have this via command but would be annoying as hell bit like Guilded online/offline situation right now.
