### ISSUE TITLE
Add bot commands to create/delete/modify voice channels

### ISSUE THREAD

**Issue by VictorNguyen00** [MarcTowler/discord-bot#67]
Start investigation of having the bot allow the ability to auto create voice channels.  

By default the voice channels should be created locked but can be unlocked given a command.

Initially channel creation should be reserved for Officers/Council only.  Possibilty to open it up more based on need.

**Comment by MarcTowler** [comment]
my thoughts on this...
voice creation, deletion and invitation is possible, to save building up invites, we could run a custom role called "fireteam chat" or something then the bot could assign the role to the voice channel and the officer could do something like !voice createlobby @user1 @user2 @user3 to create and !voice deletelobby CHANNEL NAME which unassigns the roles.

@VictorNguyen00 wants `you should be able to add a listener that deletes the channel if it has been empty for a period of time 3 minutes roughly`

**Comment by MarcTowler** [comment]
So not perfect, create and invite works fine, no need for a delete command as the channel will remove itself after 3 minutes of noone in the channel...
I cant add a role restriction as Discord's API is playing up with that, @VictorNguyen00 could you, when you remove the redundant VOIP channels restrict the VOIP category to the fireteam role

**Comment by MarcTowler** [comment]
Invite done, pushing shortly, closing issue
