### ISSUE TITLE
Bungie Roster Update

### ISSUE THREAD

**Issue by Kayowin** [MarcTowler/discord-bot#69]
To be able to remove/update a bungie member status by triggering a command, bot will look up current clan rosters, match requested input against roster and update status. Not required to match @name as they will not always match 100%

<!bungieKick andy-the-fish>
<!bungiePromote KillerAuzzie>
<!bungieDemote Sig_Shezza>

Also - _IF_ functionality is available but not essential

<!bungieAccept><new application>
<!bungieDeny><new application>

Rosters are already compiled by Azure - perhaps a shortcut available there?

**Comment by MarcTowler** [comment]
This is going to be a bit more long term, so placing it on hold for the minute

**Comment by MarcTowler** [comment]
Will need to call 
https://bungie-net.github.io/multi/operation_post_GroupV2-KickMember.html#operation_post_GroupV2-KickMember
https://bungie-net.github.io/multi/operation_post_GroupV2-EditGroupMembership.html#operation_post_GroupV2-EditGroupMembership

**Comment by MarcTowler** [comment]
Will take a proper look at this over the beginning of June

**Comment by Kayowin** [comment]
closing - multiple shared accounts no longer available
