### ISSUE TITLE
Create Command for outstanding !eventrequest

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/discord-bot#72]
**Is your feature request related to a problem? Please describe.**
[22:07] Kayowin: What if there was an officer specific command which pulled outstanding requests for their platform from the last 7 days...

**Additional context**
Data is only stored in google docs, could look at one of two things:
1. Store event requests in the API database then need to implement #52 to update an event being taken
2. pull from the sheet if an officer has not been assigned

**Comment by kolkonos** [comment]
If the event is stored on azure, it would be easy to pull the list of requests that do not have an officer assigned

**Comment by MarcTowler** [comment]
As this will be the way going forward it seems, we should look at implementing that

**Comment by kolkonos** [comment]
I’ll implement it this coming week. I feel we should have multiple ways to poll data. For instance:
1: by clan
2: by platform 
3: by bungie username
4: by discord ID

And combinations there of. 
We should enumerate the necessary methods.

**Comment by kolkonos** [comment]
Also, we should distinguish between upcoming for officers and for members. Officers should have a way to see if there are any requested events with no officer assigned and overflowing events that could be split off
