### ISSUE TITLE
Automate onboarding

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/discord-bot#84]
Automate some parts of onboarding in #pending_pool....
Flow:

1) user joins Discord
2) Bot welcomes user, posts embed (embed updated for clan events link), prompts user to (either depending on decision) use !check or tick a set emoji
3) Bot pings Azure endpoint to check that they have linked discord & checks G4G division applied for
4) IF
4a) User has linked discord with Azure & applied for division - Clan Council pinged to confirm which Division (and if it still needs approving on Bungie) and that the link is done, just age to confirm
4b) Replies to user in #pending_pool what still needs doing before progressing

FEEDBACK NEEDED @VictorNguyen00 @Kayowin @P-Rigz - 
Do we want !check command or emoji (tick) for check
Do we want to skip over age check and fully automate so when check is done, auto add the appropriate roles

**Comment by Kayowin** [comment]
partial automation is preferable, age verification still manual.

I'd say tick emoji but will defer to consensus

**Comment by MarcTowler** [comment]
Completed, pushing code changes
